name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WIFI_SSID: "test"
  WIFI_PASSWORD: "test"
  MQTT_BROKER_URL: "mqtts://example.com"
  MQTT_USER: "test"
  MQTT_PASSWORD: "test"

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir:
          - spi_display_example
          - mqtt_example
        action:
          - command: build
            args: --release
          - command: fmt
            args: --all -- --check --color always
          - command: clippy
            args: --all-targets --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32
          ldproxy: true
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Run command
        run: |
          cd ${{ matrix.dir }}
          
          cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
